[versions]
activityCompose = "1.11.0"
agp = "8.12.3"
appcompat = "1.7.1"
coil = "3.3.0"
coreKtx = "1.17.0"
datastoreCore = "1.1.7"
datastorePreferences = "1.1.7"
espressoCore = "3.7.0"
icons = "1.7.8"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.20"
libsu = "6.0.0"
material = "1.13.0"
material3 = "1.4.0"
runtime = "1.9.4"
ui-tooling = "1.9.4"
ui-tooling-preview = "1.9.4"


[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
androidx-datastore-preferences = {group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences"}
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-meterial-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "icons"}
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "ui-tooling-preview" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
libsu-io = { group = "com.github.topjohnwu.libsu", name = "io", version.ref = "libsu" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }